### ISSUE TITLE
METROTABCONTROL ISSUE

### ISSUE THREAD

**Issue by arcyeco** [N-a-r-w-i-n/MetroSet-UI#31]
HOPE YOU FINE DEAR,

PLEASE HELP ME WITH MY ISSUE\

I AM USING THE LAST METROSET-UI CONTROLS BUT WHEN I TRY TO USE `METROSETTABCONTROL` AND CHANG ANY PROPERTY IN THE DESIGNER I FACE AN ISSUES SPECIALLY WHEN I TRY TO CHANGE THE `STYLE `OR THE `TABSTYLE `PROPERTY, 

- NO PROBLEM WHILE `BUILDING `THE PROJECT

- NOT USING `STYLEMANAGER`

- THE ISSUE APEARS IN THE `RUNTIME`

THE ERROR MESSAGE IS:

> System.InvalidOperationException
  HResult=0x80131509
  Message=An error occurred creating the form. See Exception.InnerException for details.  The error is:    at MetroSet_UI.Controls.MetroSetTabControl.InvalidateTabPage(Color c)
   at MetroSet_UI.Controls.MetroSetTabControl.UpdateProperties()
  Source=Crowe_Loans_Analyses
  StackTrace:
   at Crowe_Loans_Analyses.My.MyProject.MyForms.Create__Instance__[T](T Instance) in :line 190
   at Crowe_Loans_Analyses.My.MyProject.MyForms.get_Frm_Main_Dashboard()
   at Crowe_Loans_Analyses.My.MyApplication.OnCreateMainForm() in D:\Application projects\OTHERS\Crowe_Loans_Analyses_03_04_001\Crowe_Loans_Analyses\My Project\Application.Designer.vb:line 35
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at Crowe_Loans_Analyses.My.MyApplication.Main(String[] Args) in :line 81

Inner Exception 1:
Exception:    at MetroSet_UI.Controls.MetroSetTabControl.InvalidateTabPage(Color c)
   at MetroSet_UI.Controls.MetroSetTabControl.UpdateProperties()

![2020-04-03 (2)](https://user-images.githubusercontent.com/6111343/78314806-bcebbf00-7563-11ea-8cb2-25c2027cf115.png)
![2020-04-03 (3)](https://user-images.githubusercontent.com/6111343/78314809-bf4e1900-7563-11ea-8df8-d18f58ef289a.png)
![2020-04-03 (4)](https://user-images.githubusercontent.com/6111343/78314810-c07f4600-7563-11ea-8608-ffd1e24aa7f2.png)

THANKS IN ADVANCE

**Comment by arcyeco** [comment]
؟؟؟؟

**Comment by arcyeco** [comment]
Could i get help please?

**Comment by N-a-r-w-i-n** [comment]
Are you trying to set style manager to non-MetroSetForm with having MetroSetTabControl in it? in that case style manager encounters issues to set the properties.
